## Importing NumPy

In [3]:
import numpy as np

### Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [6]:
arr = np.array([1, 2, 3, 6, 4, 5])
print(f"{arr} reverse is {np.flip(arr)}")

[1 2 3 6 4 5] reverse is [5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [7]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(f"{array1} flattened is: {array1.flatten()}")

[[1 2 3]
 [2 4 5]
 [1 2 3]] flattened is: [1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [12]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(f"""Comparing
arr1: {arr1}
 and
arr2: {arr2}
Comparison: {np.equal(arr1, arr2)}""")

Comparing
arr1: [[1 2]
 [3 4]]
 and
arr2: [[1 2]
 [3 4]]
Comparison: [[ True  True]
 [ True  True]]


(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [25]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(f"Most frequent element in {x} is: {np.bincount(x).argmax()} at indice(s): {np.where(x == np.bincount(x).argmax())}")
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
print(f"Most frequent element in {y} is: {np.bincount(y).argmax()} at indice(s): {np.where(y == np.bincount(y).argmax())}")

Most frequent element in [1 2 3 4 5 1 2 1 1 1] is: 1 at indice(s): (array([0, 5, 7, 8, 9], dtype=int64),)
Most frequent element in [1 1 1 2 3 4 2 4 3 3] is: 1 at indice(s): (array([0, 1, 2], dtype=int64),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

In [32]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(f"Sum of all elements: {np.sum(gfg)}")
print(f"Sum of all elements row wise: \n{np.sum(gfg, axis=1)}")
print(f"Sum of all elements column wise: \n{np.sum(gfg, axis=0)}")

Sum of all elements: 45
Sum of all elements row wise: 
[[14]
 [16]
 [15]]
Sum of all elements column wise: 
[[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix

In [46]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(n_array)
v, w = np.linalg.eig(n_array)
print(f"Sum of diagonal elements: {np.trace(n_array)}")
print(f"Eigen values of matrix: \n{v}")
print(f"Eigen vectors of matrix: \n{w}")
print(f"Inverse of matrix: \n{np.linalg.inv(n_array)}")
print(f"Determinant of a matrix: {np.linalg.det(n_array)}")

[[55 25 15]
 [30 44  2]
 [11 45 77]]
Sum of diagonal elements: 176
Eigen values of matrix: 
[98.16835147 28.097044   49.73460452]
Eigen vectors of matrix: 
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix: 
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of a matrix: 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [56]:
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print(f"Multiplication of {p} x {q} \n= {np.matmul(p, q)}")
print(f"Covariance of {p} and {q} is: {np.cov(p, q)[0][1]}")
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
print(f"Multiplication of {p} x {q} \n= {np.matmul(p, q)}")
print(f"Size of {p} != size of {q}, hence we cannot find covariance between the two")

Multiplication of [[1, 2], [2, 3]] x [[4, 5], [6, 7]] 
= [[16 19]
 [26 31]]
Covariance of [[1, 2], [2, 3]] and [[4, 5], [6, 7]] is: 0.5
Multiplication of [[1, 2], [2, 3], [4, 5]] x [[4, 5, 1], [6, 7, 2]] 
= [[16 19  5]
 [26 31  8]
 [46 55 14]]
Size of [[1, 2], [2, 3], [4, 5]] != size of [[4, 5, 1], [6, 7, 2]], hence we cannot find covariance between the two


For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [69]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(f"X = {x}")
print(f"Y = {y}")
print(f"Inner product = \n{np.inner(x, y)}")
print(f"Outer product = \n{np.outer(x, y)}")
#print(f"Cartesian product = {np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])}")

X = [[2 3 4]
 [3 2 9]]
Y = [[ 1  5  0]
 [ 5 10  3]]
Inner product = 
[[17 52]
 [13 62]]
Outer product = 
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product = [array([[2, 3, 4, 2, 3, 4],
        [3, 2, 9, 3, 2, 9]])
 array([ 1,  1,  5,  5,  0,  0,  5,  5, 10, 10,  3,  3])]


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


### Q2: Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [7]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(f"Absolute value: \n{np.absolute(array)}")

Absolute value: 
[[1 2 3]
 [4 5 6]]


In [9]:
print(f"25th percentile of flattened array is {np.percentile(array.flatten(), 25)}")
print(f"50th percentile of flattened array is {np.percentile(array.flatten(), 50)}")
print(f"75th percentile of flattened array is {np.percentile(array.flatten(), 75)}")

25th percentile of array is -3.5
50th percentile of array is -0.5
75th percentile of array is 2.5


In [10]:
for i in array:
    print(f"25th percentile of {i} is {np.percentile(i, 25)}")
    print(f"50th percentile of {i} is {np.percentile(i, 50)}")
    print(f"75th percentile of {i} is {np.percentile(i, 75)}")

25th percentile of [ 1 -2  3] is -0.5
50th percentile of [ 1 -2  3] is 1.0
75th percentile of [ 1 -2  3] is 2.0
25th percentile of [-4  5 -6] is -5.0
50th percentile of [-4  5 -6] is -4.0
75th percentile of [-4  5 -6] is 0.5


In [14]:
for i in range(0, len(array[0])):
    print(f"25th percentile of {array[:,i]} is {np.percentile(array[:,i], 25)}")
    print(f"50th percentile of {array[:,i]} is {np.percentile(array[:,i], 50)}")
    print(f"75th percentile of {array[:,i]} is {np.percentile(array[:,i], 75)}")

25th percentile of [ 1 -4] is -2.75
50th percentile of [ 1 -4] is -1.5
75th percentile of [ 1 -4] is -0.25
25th percentile of [-2  5] is -0.25
50th percentile of [-2  5] is 1.5
75th percentile of [-2  5] is 3.25
25th percentile of [ 3 -6] is -3.75
50th percentile of [ 3 -6] is -1.5
75th percentile of [ 3 -6] is 0.75


In [19]:
print(f"Mean for \n{array} is {array.mean()}")
print(f"Median for \n{array} is {np.median(array)}")
print(f"Standard Deviation for \n{array} is {array.std()}")

Mean for 
[[ 1 -2  3]
 [-4  5 -6]] is -0.5
Median for 
[[ 1 -2  3]
 [-4  5 -6]] is -0.5
Standard Deviation for 
[[ 1 -2  3]
 [-4  5 -6]] is 3.8622100754188224


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [24]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(f"Values floored: {np.floor(a)}")
print(f"Values ceiled: {np.ceil(a)}")
print(f"Rounded values: {np.round(a)}")
print(f"Truncated values: {np.trunc(a)}")

Values floored: [-2. -2. -1.  0.  1.  1.  3.]
Values ceiled: [-1. -1. -0.  1.  2.  2.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]


### Q3: Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements

In [30]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
array = np.sort(array)
print(f"Sorted array: {array}")
print(f"4 smallest elements: {array[0:4]}")
print(f"5 largest elements: {array[-5:]}")

Sorted array: [ 10  16  16  52  54  62 453]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only

In [38]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Integer values")
for i in array:
    if i % 1 == 0:
        print(i)

print("Float values")
for i in array:
    if i % 1 != 0:
        print(i)

Integer values
1.0
2.0
3.0
2.0
Float values
1.2
2.2


(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)
(b) Load the saved file into jupyter notebook?

In [53]:
import cv2
def img_to_array(path):
    normal = cv2.imread(path)
    grey = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

    np.save(path, normal)
    np.save(path, grey)


In [57]:
img_to_array("./SystemofaDownToxicityalbumcover.jpg")

Loading Images

In [59]:
normalLoad = np.load("./SystemofaDownToxicityalbumcover.jpg.npy")